default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Secret['POSTGRES_USER'] %>
  password: <%= Secret['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: <%= "#{ENV['DB_PREFIX']}development" %>

test:
  <<: *default
  database: <%= "#{ENV['DB_PREFIX']}test" %>

production:
  <<: *default
  database: <%= "#{ENV['DB_PREFIX']}production" %>
